### PR TITLE
Remove org members without team

### PR DESCRIPTION
**Pull request by Robbilie**
Solves #127

### CODE REVIEW

**Comment by primetheus** [comment]
@Robbilie Thanks for opening this up! Can you also update the `.env.example` files and `README`?

**Comment by Robbilie** [comment]
sure thing!

i need your opinion on my code though, i realized that it has a tiny flaw, it runs before team members get kicked out of teams so it may take until the next scheduled run to completely remove a member from the org. changing this would mean though that i would have to do the whole iterate over installations and orgs thing after future.result() loop. that would blow up the method and thus i would probably shift it to a seperate one, but it feels like a lot of duplicate code then. any thoughts?

**Comment by Robbilie** [comment]
i made that code change, i think its a bit cleaner this way even though a bit more duplicated, at least it doesnt take another schedule this way. feel free to add your thoughts :)

**Comment by primetheus** [comment]
@Robbilie it seems to work, but it may be expensive on massive infrastructures with 10k+ users, since it doubles the API calls. I'll do some testing this afternoon and see if we can optimize the performance a bit

**Comment by VanyaBerzoi** [comment]
> Solves #127

https://github.com/github/github-team-sync/pull/128#issue-1234143118

**Review by primetheus — APPROVED** [review]

**Pull request merged**
